name: Pull Request

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 19.x, 20.x, 21.x ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          run_install: false
          version: 8
      - run: pnpm install
      - run: pnpm build --if-present
      - run: pnpm test:coverage
      - name: Code Coverage
        run: npx codecov --token=${{ secrets.CODECOV_TOKEN }}
