name: Release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 19.x, 20.x, 21.x ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          run_install: false
          version: 8
      - run: pnpm install
      - run: pnpm build
      - run: pnpm test:coverage
      - name: Code Coverage
        run: pnpm exec codecov --token=${{ secrets.CODECOV_TOKEN }}

  generate-docs:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          run_install: false
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Create the docs directory locally in CI
        run: pnpm docs

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs

  release:
    needs:
      - build
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21.x
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          run_install: false
          version: 8
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          HUSKY: 0
        run: npx semantic-release
